In [1]:
import numpy as np
import mne

from hdf5storage import loadmat, savemat 

In [2]:
outdict=loadmat('../test_scripts/EEG_processing/DAON/icadata.mat')
outdict.keys()


dict_keys(['__header__', '__version__', '__globals__', 'Fs', 'badchan', 'goodchan', 'mixedsig'])

In [3]:
mixedsig=outdict['mixedsig']*0.000001
Fs=outdict['Fs'][0]
badchan=outdict['badchan'][0]-1
goodchan=outdict['goodchan'][0]-1

In [4]:
outdict=loadmat('../test_scripts/EEG_processing/DAON/good_labels.mat')
outdict.keys()

dict_keys(['__header__', '__version__', '__globals__', 'good_labels'])

In [5]:
good_labels=outdict['good_labels']

In [6]:
good_labels=good_labels[:]

In [7]:
outdict=loadmat('../test_scripts/EEG_processing/DAON/ch_labels.mat')
outdict.keys()

dict_keys(['__header__', '__version__', '__globals__', 'ch_labels'])

In [8]:
ch_labels=outdict['ch_labels']

In [9]:
# n_channels = np.shape(mixedsig)[0]
n_channels=256


In [10]:
sampling_freq = Fs  # in Hertz


In [11]:
info = mne.create_info(n_channels, sfreq=sampling_freq)
print(info)

<Info | 7 non-empty values
 bads: []
 ch_names: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, ...
 chs: 256 misc
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 500.0 Hz
 meas_date: unspecified
 nchan: 256
 projs: []
 sfreq: 1000.0 Hz
>


In [12]:
# ch_names=list()
# for i in range(n_channels):
#     ch_names.append(np.array2string(ch_labels[i][0]))
ch_names = [f"E{n}" for n in range(1, 257)]
ch_types = ["eeg"] * n_channels

In [13]:
# np.array2string(*good_labels[i])

In [14]:
ch_names

['E1',
 'E2',
 'E3',
 'E4',
 'E5',
 'E6',
 'E7',
 'E8',
 'E9',
 'E10',
 'E11',
 'E12',
 'E13',
 'E14',
 'E15',
 'E16',
 'E17',
 'E18',
 'E19',
 'E20',
 'E21',
 'E22',
 'E23',
 'E24',
 'E25',
 'E26',
 'E27',
 'E28',
 'E29',
 'E30',
 'E31',
 'E32',
 'E33',
 'E34',
 'E35',
 'E36',
 'E37',
 'E38',
 'E39',
 'E40',
 'E41',
 'E42',
 'E43',
 'E44',
 'E45',
 'E46',
 'E47',
 'E48',
 'E49',
 'E50',
 'E51',
 'E52',
 'E53',
 'E54',
 'E55',
 'E56',
 'E57',
 'E58',
 'E59',
 'E60',
 'E61',
 'E62',
 'E63',
 'E64',
 'E65',
 'E66',
 'E67',
 'E68',
 'E69',
 'E70',
 'E71',
 'E72',
 'E73',
 'E74',
 'E75',
 'E76',
 'E77',
 'E78',
 'E79',
 'E80',
 'E81',
 'E82',
 'E83',
 'E84',
 'E85',
 'E86',
 'E87',
 'E88',
 'E89',
 'E90',
 'E91',
 'E92',
 'E93',
 'E94',
 'E95',
 'E96',
 'E97',
 'E98',
 'E99',
 'E100',
 'E101',
 'E102',
 'E103',
 'E104',
 'E105',
 'E106',
 'E107',
 'E108',
 'E109',
 'E110',
 'E111',
 'E112',
 'E113',
 'E114',
 'E115',
 'E116',
 'E117',
 'E118',
 'E119',
 'E120',
 'E121',
 'E122',
 'E123',
 

In [15]:
# good_labels[i]

In [16]:
info = mne.create_info(ch_names, ch_types=ch_types, sfreq=sampling_freq)


In [17]:
# info.set_montage("GSN-HydroCel-256",match_case=False,match_alias=False,on_missing='raise')
info.set_montage("GSN-HydroCel-256",match_case=False,match_alias=False,on_missing='raise')
print(info)

<Info | 8 non-empty values
 bads: []
 ch_names: E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, ...
 chs: 256 EEG
 custom_ref_applied: False
 dig: 259 items (3 Cardinal, 256 EEG)
 highpass: 0.0 Hz
 lowpass: 500.0 Hz
 meas_date: unspecified
 nchan: 256
 projs: []
 sfreq: 1000.0 Hz
>


In [18]:
info['dig']

[<DigPoint |        LPA : (-77.5, 0.0, 0.0) mm      : head frame>,
 <DigPoint |     Nasion : (0.0, 101.5, -0.0) mm     : head frame>,
 <DigPoint |        RPA : (77.5, 0.0, 0.0) mm       : head frame>,
 <DigPoint |     EEG #1 : (68.9, 50.7, 7.2) mm      : head frame>,
 <DigPoint |     EEG #2 : (64.2, 64.1, 25.5) mm     : head frame>,
 <DigPoint |     EEG #3 : (56.4, 75.1, 43.0) mm     : head frame>,
 <DigPoint |     EEG #4 : (47.6, 83.7, 60.3) mm     : head frame>,
 <DigPoint |     EEG #5 : (35.8, 83.9, 78.9) mm     : head frame>,
 <DigPoint |     EEG #6 : (22.3, 76.3, 94.8) mm     : head frame>,
 <DigPoint |     EEG #7 : (11.8, 66.1, 108.2) mm    : head frame>,
 <DigPoint |     EEG #8 : (0.0, 51.3, 116.9) mm     : head frame>,
 <DigPoint |     EEG #9 : (-11.4, 31.7, 124.7) mm   : head frame>,
 <DigPoint |    EEG #10 : (58.8, 71.3, 10.5) mm     : head frame>,
 <DigPoint |    EEG #11 : (50.3, 84.2, 27.6) mm     : head frame>,
 <DigPoint |    EEG #12 : (38.4, 94.1, 47.1) mm     : head fra

In [19]:
outdict=loadmat('../EEG_pipeline/egi_xyz.mat')
Coordinates=outdict['Coordianates']/1000
for ch in range(3,len(info['dig'])):
    info['dig'][ch]['r']=Coordinates[ch-3,:]

In [20]:
# outdict=loadmat('../EEG_pipeline/egi_xyz.mat')
# Coordinates=outdict['Coordianates']

In [21]:
info["description"] = "My egi dataset"

In [22]:
outdict=loadmat('../test_scripts/EEG_processing/DAON/ch_bad.mat')
ch_bad=outdict['ch_bad'][0]-1
np.shape(ch_bad)

(49,)

In [23]:
ch_bad

array([240, 241, 242, 237, 238, 239, 243, 244, 245, 246, 250, 255,  90,
       101, 110, 119, 132, 144, 164, 173, 186, 198, 207, 215, 228, 232,
       236, 235, 234, 233, 231, 227, 216, 208, 199, 187, 174, 165, 155,
       145, 133, 120, 111, 102,  91,  81, 254, 249, 256], dtype=uint16)

In [24]:
ch_bad=np.delete(ch_bad,48,0)

In [25]:
np.shape(ch_bad)

(48,)

In [26]:
ch_bad

array([240, 241, 242, 237, 238, 239, 243, 244, 245, 246, 250, 255,  90,
       101, 110, 119, 132, 144, 164, 173, 186, 198, 207, 215, 228, 232,
       236, 235, 234, 233, 231, 227, 216, 208, 199, 187, 174, 165, 155,
       145, 133, 120, 111, 102,  91,  81, 254, 249], dtype=uint16)

In [27]:
info['bads'] = [ch_names[k] for k in ch_bad]

In [29]:
info['bads']

['E241',
 'E242',
 'E243',
 'E238',
 'E239',
 'E240',
 'E244',
 'E245',
 'E246',
 'E247',
 'E251',
 'E256',
 'E91',
 'E102',
 'E111',
 'E120',
 'E133',
 'E145',
 'E165',
 'E174',
 'E187',
 'E199',
 'E208',
 'E216',
 'E229',
 'E233',
 'E237',
 'E236',
 'E235',
 'E234',
 'E232',
 'E228',
 'E217',
 'E209',
 'E200',
 'E188',
 'E175',
 'E166',
 'E156',
 'E146',
 'E134',
 'E121',
 'E112',
 'E103',
 'E92',
 'E82',
 'E255',
 'E250']

In [30]:
# insert ch_bad with signal of zeros
data=np.zeros((256,np.shape(mixedsig)[1]))
i=0
for c in range(256):
    if c not in ch_bad:
        data[c,:]=mixedsig[i,:]
        i+=1

In [ ]:
# good_coordinates=np.copy(Coordinates)

In [ ]:
# good_coordinates=np.delete(good_coordinates,ch_bad,0)

In [ ]:
# good_coordinates[0,:]

In [ ]:
# print(ch_names[i])

In [31]:
raw = mne.io.RawArray(data, info)
raw.plot(show_scrollbars=False, show_scalebars=False)

Creating RawArray with float64 data, n_channels=256, n_times=182000
    Range : 0 ... 181999 =      0.000 ...   181.999 secs
Ready.


Using qt as 2D backend.


qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""


In [32]:
raw.info['bads']

['E241',
 'E242',
 'E243',
 'E238',
 'E239',
 'E240',
 'E244',
 'E245',
 'E246',
 'E247',
 'E251',
 'E256',
 'E91',
 'E102',
 'E111',
 'E120',
 'E133',
 'E145',
 'E165',
 'E174',
 'E187',
 'E199',
 'E208',
 'E216',
 'E229',
 'E233',
 'E237',
 'E236',
 'E235',
 'E234',
 'E232',
 'E228',
 'E217',
 'E209',
 'E200',
 'E188',
 'E175',
 'E166',
 'E156',
 'E146',
 'E134',
 'E121',
 'E112',
 'E103',
 'E92',
 'E82',
 'E255',
 'E250']

In [ ]:
# for i in range(len(ch_bad)):
#     raw.drop_channels(ch_names(ch_bad[i].astype(int)))

In [33]:
ch_bad.astype(int)

array([240, 241, 242, 237, 238, 239, 243, 244, 245, 246, 250, 255,  90,
       101, 110, 119, 132, 144, 164, 173, 186, 198, 207, 215, 228, 232,
       236, 235, 234, 233, 231, 227, 216, 208, 199, 187, 174, 165, 155,
       145, 133, 120, 111, 102,  91,  81, 254, 249])

In [34]:
raw.set_eeg_reference('average', projection=True)

EEG channel type selected for re-referencing
Adding average EEG reference projection.
1 projection items deactivated
Average reference projection was added, but has not been applied yet. Use the apply_proj method to apply it.


<RawArray | 256 x 182000 (182.0 s), ~355.8 MB, data loaded>

In [ ]:
# raw = mne.io.RawArray(mixedsig, info)
# raw.plot(show_scrollbars=False, show_scalebars=False)

In [ ]:
# # https://mne.tools/dev/generated/mne.channels.make_dig_montage.html

# lpa=np.array([-77.5, 0.0, 0.0])
# nasion=np.array([0.0, 101.5, -0.0])
# rpa=np.array([77.5, 0.0, 0.0])

# ch_pos=dict() 
# for r in range(np.shape(good_coordinates)[0]):
#     ch_pos[ch_names[r]]=good_coordinates[r,:]


In [ ]:
# np.shape(good_coordinates)[0]

In [ ]:
# EGI_208=mne.channels.make_dig_montage(ch_pos=ch_pos, nasion=nasion, lpa=lpa, rpa =rpa)

In [ ]:
# mne.viz.plot_montage(EGI_208)

In [ ]:
# raw.set_montage("EGI_208",match_case=False,match_alias=False,on_missing='raise')

In [66]:
len(info['dig'])

259

In [35]:
raw.save("egi_raw.fif",overwrite=True)

Overwriting existing file.
Writing /home/zhibinz2/Documents/GitHub/MEG_EEG_Source_Localization/goodchanEGI_pipeline/egi_raw.fif
Closing /home/zhibinz2/Documents/GitHub/MEG_EEG_Source_Localization/goodchanEGI_pipeline/egi_raw.fif
[done]


In [3]:
# This will open a GUI to manually create a transformation matrix file
mne.gui.coregistration()
# I have did this and save the file as DAON_trans.fif in this directory

Using pyvistaqt 3d backend.



qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""


    Triangle neighbors and vertex normals...
Using low resolution head model in /home/zhibinz2/mne_data/MNE-sample-data/subjects/ANTS6-0Months3T/bem/outer_skin.surf
    Triangle neighbors and vertex normals...
Using fiducials from: /home/zhibinz2/mne_data/MNE-sample-data/subjects/ANTS6-0Months3T/bem/ANTS6-0Months3T-fiducials.fif.
    Triangle neighbors and vertex normals...
Using low resolution head model in /home/zhibinz2/mne_data/MNE-sample-data/subjects/ANTS6-0Months3T/bem/outer_skin.surf
    Triangle neighbors and vertex normals...
Using fiducials from: /home/zhibinz2/mne_data/MNE-sample-data/subjects/ANTS6-0Months3T/bem/ANTS6-0Months3T-fiducials.fif.
Loading MRI fiducials from /home/zhibinz2/mne_data/MNE-sample-data/subjects/ANTS6-0Months3T/bem/ANTS6-0Months3T-fiducials.fif... Done!
Using outer_skin.surf for head surface.
Loading MRI fiducials from /home/zhibinz2/mne_data/MNE-sample-data/subjects/ANTS6-0Months3T/bem/ANTS6-0Months3T-fiducials.fif... Done!
Using outer_skin.surf for 